### ISSUE TITLE
Pretrained model for VQGAN

### ISSUE THREAD

**Issue by choyingw** [dome272/MaskGIT-pytorch#11]
Thank you for the implementation! I would like to tune the second-stage transformer, but my VQGAN trained on Flickr landscape dataset is not so good. I see there is a load function of 'vq_flickr.pt' and you have much better landscape results. Could you kindly share that? Thanks!

![out_2](https://user-images.githubusercontent.com/43560997/176980414-941126e2-bd01-4eb8-97a7-6af6aa62e547.jpg)

**Comment by dome272** [comment]
I dont have a pretrained flickr lying around anymore, but you may wanna take a look at concurrent work for the paper Make-A-Scene where we have released some ckpt. In the colab I also use rudalle and taming-transformer. All of these are general purpose models and should work pretty good for flickr. https://colab.research.google.com/drive/1SPyQ-epTsAOAu8BEohUokN4-b5RM_TnE?usp=sharing

**Comment by choyingw** [comment]
Thank you for the quick response!
